name: ublue-laptop
description: ""
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/repo/fedora-39/secureblue-hardened_malloc-fedora-39.repo
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/brave-browser.repo
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/protonvpn-stable.repo
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - pavucontrol
        - pipewire-codec-aptx
        - hardened_malloc
        - brave-browser
        - aircrack-ng
        - c-ares
        - compat-lua-libs
        - dbus-daemon
        - dbus-tools
        - dbus-x11
        - hwloc-libs
        - iw
        - libmaxminddb
        - libsmi
        - macchanger
        - wireshark-cli
        - aircrack-ng-doc
        - proton-vpn-gnome-desktop
        - freerdp
        - virt-manager
    optfix: 
        - brave.com
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true 
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.mozilla.firefox
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - com.github.d4nj1.tlpui
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.jetbrains.Rider
        - io.github.shiftey.Desktop

  - type: bling
    install:  
        - laptop
  - type: script
    scripts:
        - setfilepermissions.sh
  - type: signing
