name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/protonvpn-stable.repo
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - proton-vpn-gnome-desktop
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - io.freetubeapp.FreeTube
        - org.kde.okular
        - org.qbittorrent.qBittorrent  
  - type: script
    scripts:
        - chromium_laptop.sh
  - type: signing
