name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: 39 

modules:
  - type: rpm-ostree
    repos:
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - pavucontrol
        - pipewire-codec-aptx
        - aircrack-ng
        - c-ares
        - compat-lua-libs
        - dbus-daemon
        - dbus-tools
        - dbus-x11
        - hwloc-libs
        - iw
        - libmaxminddb
        - libsmi
        - macchanger
        - wireshark-cli
        - aircrack-ng-doc

  - type: files
    files:
      - usr: /usr
     
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.jetbrains.Rider
        - com.protonvpn.www
        
  - type: script
    scripts:
        - setfilepermissions.sh
        - chromium.sh
        - bluetooththunder.sh
  - type: signing
