name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/aurora-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/protonvpn-stable.repo
    install:
        - zsh
        - neovim
        - easyeffects
        - proton-vpn-gnome-desktop
        - rsms-inter-fonts
    remove:
        - input-leap
        - input-remapper
        - tailscale
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.qbittorrent.qBittorrent
        - com.visualstudio.code
        - org.kde.gwenview
        - org.kde.okular

  - type: script
    scripts:
        - chromium_laptop.sh
  - type: signing
