name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/silverblue-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    optfix:
        - brave.com
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - fastfetch
        - brave-browser
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.qbittorrent.qBittorrent
        - com.github.tchx84.Flatseal

  - type: script
    scripts:
        - chromium_laptop.sh
  - type: signing
