name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - fastfetch
        - https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.rpm
      
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.qbittorrent.qBittorrent
        - org.kde.okular
        - com.jetbrains.Rider

  - type: script
    scripts:
        - chromium_laptop.sh
  - type: signing
