name: ublue-pc
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
    install:
        - zsh
        - neovim
        - solaar
        - corectrl
        - fastfetch
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - io.github.shiftey.Desktop
        - org.kde.okular

  - type: script
    scripts:
      - chromium_desktop.sh
  - type: signing
