name: ublue-laptop
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: br-f40-40

modules:
  - type: rpm-ostree
    repos:
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - pavucontrol
        - pipewire-codec-aptx
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.jetbrains.Rider
        - com.protonvpn.www
        - io.github.shiftey.Desktop
  
  - type: script
    scripts:
        - chromium.sh
        - bluetooththunder.sh
  - type: signing
