name: ublue-laptop
description: ""
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 

modules:
  - type: rpm-ostree
    repos:
        - https://copr.fedorainfracloud.org/coprs/secureblue/hardened_malloc/repo/fedora-39/secureblue-hardened_malloc-fedora-39.repo
    install:
        - zsh
        - neovim
        - easyeffects
        - solaar
        - pavucontrol
        - pipewire-codec-aptx
        - hardened_malloc
        - chromium
        - aircrack-ng
        - c-ares
        - compat-lua-libs
        - dbus-daemon
        - dbus-tools
        - dbus-x11
        - hwloc-libs
        - iw
        - libmaxminddb
        - libsmi
        - macchanger
        - wireshark-cli
        - aircrack-ng-doc
    remove:
      - firefox
      - firefox-langpacks
  - type: files
    files:
      - usr: /usr
     
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.jetbrains.Rider
        - com.protonvpn.www
        
  - type: script
    scripts:
        - setfilepermissions.sh
  - type: signing
