name: ublue-pc
description: ""
base-image: ghcr.io/secureblue/kinoite-main-userns-hardened
image-version: latest

modules:
  - type: rpm-ostree
    repos:
        - https://raw.githubusercontent.com/MkKvcs/fedora/main/protonvpn-stable.repo
    install:
        - zsh
        - neovim
        - solaar
        - corectrl
        - proton-vpn-gnome-desktop
        
  - type: default-flatpaks
    notify: true 
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.spotify.Client
        - com.discordapp.Discord
        - org.signal.Signal
        - org.qbittorrent.qBittorrent
        - org.videolan.VLC
        - org.fedoraproject.MediaWriter
        - org.onlyoffice.desktopeditors
        - com.visualstudio.code
        - io.github.shiftey.Desktop
        - org.kde.okular
        - io.freetubeapp.FreeTube

  - type: script
    scripts:
        - chromium.sh
        - bluetooththunder.sh
  - type: signing
